import requests, json

resp = requests.post('http://localhost:8000/api/auth/login', json={'email':'marie.dossou@sante.com','password':'admin123'})
token = resp.json()['access_token']
headers = {'Authorization': f'Bearer {token}'}

CASES = [
  {'expected':'Hypertension','age':55,'sexe':'M','sev':'MODERE','duree':90,'vitaux':{'tension_systolique':165,'tension_diastolique':100,'frequence_cardiaque':82,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':97,'poids':92,'taille':175},'symptomes':['Maux de tête','Maux de tête matinaux','Hypertension','Vertiges','Palpitations'],'examens':[{'nom':'Créatinine','valeur_numerique':1.2,'unite_mesure':'mg/dL'},{'nom':'Potassium','valeur_numerique':4.2,'unite_mesure':'mEq/L'},{'nom':'Glucose à jeun','valeur_numerique':105,'unite_mesure':'mg/dL'},{'nom':'Cholestérol total','valeur_numerique':220,'unite_mesure':'mg/dL'}]},
  {'expected':'Infarctus du myocarde','age':62,'sexe':'M','sev':'CRITIQUE','duree':1,'vitaux':{'tension_systolique':95,'tension_diastolique':60,'frequence_cardiaque':110,'temperature':37.2,'frequence_respiratoire':22,'saturation_oxygene':93,'poids':85,'taille':172},'symptomes':['Douleur thoracique sévère','Douleur au bras épaule','Sueurs froides','Nausées','Essoufflement soudain','Palpitations'],'examens':[{'nom':'Troponine','valeur_numerique':2.5,'unite_mesure':'ng/mL'},{'nom':'CK','valeur_numerique':450,'unite_mesure':'U/L'},{'nom':'Myoglobine','valeur_numerique':180,'unite_mesure':'ng/mL'}]},
  {'expected':'Insuffisance cardiaque','age':70,'sexe':'F','sev':'SEVERE','duree':30,'vitaux':{'tension_systolique':145,'tension_diastolique':88,'frequence_cardiaque':98,'temperature':36.8,'frequence_respiratoire':24,'saturation_oxygene':91,'poids':78,'taille':162},'symptomes':['Essoufflement','Gonflement des chevilles','Œdèmes','Fatigue','Dyspnée','Toux sèche'],'examens':[{'nom':'BNP','valeur_numerique':850,'unite_mesure':'pg/mL'},{'nom':'ProBNP','valeur_numerique':4500,'unite_mesure':'pg/mL'},{'nom':'Créatinine','valeur_numerique':1.4,'unite_mesure':'mg/dL'}]},
  {'expected':'Arythmie cardiaque','age':48,'sexe':'M','sev':'MODERE','duree':3,'vitaux':{'tension_systolique':125,'tension_diastolique':78,'frequence_cardiaque':148,'temperature':36.9,'frequence_respiratoire':18,'saturation_oxygene':96,'poids':80,'taille':178},'symptomes':['Palpitations',"Sensation d'accélération",'Vertiges','Essoufflement','Fatigue','Syncope'],'examens':[{'nom':'Potassium','valeur_numerique':3.2,'unite_mesure':'mEq/L'}]},
  {'expected':'Angine de poitrine','age':58,'sexe':'M','sev':'MODERE','duree':14,'vitaux':{'tension_systolique':138,'tension_diastolique':85,'frequence_cardiaque':78,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':97,'poids':88,'taille':175},'symptomes':['Douleur thoracique',"Douleur à l'effort",'Oppression thoracique','Douleur au bras','Essoufflement'],'examens':[{'nom':'Troponine','valeur_numerique':0.02,'unite_mesure':'ng/mL'},{'nom':'Cholestérol LDL','valeur_numerique':160,'unite_mesure':'mg/dL'},{'nom':'Cholestérol total','valeur_numerique':240,'unite_mesure':'mg/dL'}]},
  {'expected':'Asthme','age':22,'sexe':'F','sev':'MODERE','duree':7,'vitaux':{'tension_systolique':118,'tension_diastolique':72,'frequence_cardiaque':102,'temperature':37.1,'frequence_respiratoire':26,'saturation_oxygene':93,'poids':58,'taille':165},'symptomes':['Respiration sifflante','Toux sèche','Difficulté à respirer','Oppression thoracique','Essoufflement','Toux nocturne'],'examens':[{'nom':'Eosinophiles','valeur_numerique':8,'unite_mesure':'%'}]},
  {'expected':'Pneumonie','age':45,'sexe':'M','sev':'SEVERE','duree':5,'vitaux':{'tension_systolique':105,'tension_diastolique':65,'frequence_cardiaque':112,'temperature':39.4,'frequence_respiratoire':28,'saturation_oxygene':89,'poids':75,'taille':172},'symptomes':['Fièvre élevée','Toux avec expectorations','Douleur thoracique pleurétique','Difficulté à respirer','Frissons','Fatigue'],'examens':[{'nom':'Globules Blancs','valeur_numerique':18.5,'unite_mesure':'K/µL'},{'nom':'Neutrophiles','valeur_numerique':88,'unite_mesure':'%'},{'nom':'CRP','valeur_numerique':145,'unite_mesure':'mg/L'}]},
  {'expected':'BPCO','age':68,'sexe':'M','sev':'SEVERE','duree':180,'vitaux':{'tension_systolique':135,'tension_diastolique':80,'frequence_cardiaque':90,'temperature':37.2,'frequence_respiratoire':22,'saturation_oxygene':88,'poids':65,'taille':170},'symptomes':['Toux persistante','Toux avec expectorations','Essoufflement','Dyspnée','Respiration sifflante','Fatigue'],'examens':[{'nom':'Globules Rouges','valeur_numerique':5.8,'unite_mesure':'M/µL'},{'nom':'Hémoglobine','valeur_numerique':17.2,'unite_mesure':'g/dL'}]},
  {'expected':'Tuberculose','age':35,'sexe':'M','sev':'SEVERE','duree':45,'vitaux':{'tension_systolique':110,'tension_diastolique':68,'frequence_cardiaque':95,'temperature':38.3,'frequence_respiratoire':20,'saturation_oxygene':94,'poids':55,'taille':170},'symptomes':['Toux persistante','Hémoptysie','Sueurs nocturnes','Perte de poids','Fièvre intermittente','Fatigue'],'examens':[]},
  {'expected':'COVID-19','age':40,'sexe':'F','sev':'MODERE','duree':8,'vitaux':{'tension_systolique':120,'tension_diastolique':75,'frequence_cardiaque':95,'temperature':38.8,'frequence_respiratoire':22,'saturation_oxygene':92,'poids':68,'taille':163},'symptomes':['Fièvre','Toux sèche','Perte de goût',"Perte d'odorat",'Fatigue','Difficulté à respirer'],'examens':[{'nom':'Lymphocytes','valeur_numerique':12,'unite_mesure':'%'},{'nom':'CRP','valeur_numerique':88,'unite_mesure':'mg/L'}]},
  {'expected':'Diabète Type 2','age':52,'sexe':'M','sev':'MODERE','duree':60,'vitaux':{'tension_systolique':142,'tension_diastolique':88,'frequence_cardiaque':80,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':97,'poids':98,'taille':174},'symptomes':['Soif excessive','Fréquence urinaire','Fatigue','Perte de poids','Vision floue','Cicatrisation lente'],'examens':[{'nom':'Glucose à jeun','valeur_numerique':186,'unite_mesure':'mg/dL'},{'nom':'HbA1c','valeur_numerique':9.2,'unite_mesure':'%'},{'nom':'Créatinine','valeur_numerique':1.1,'unite_mesure':'mg/dL'},{'nom':'Cholestérol total','valeur_numerique':235,'unite_mesure':'mg/dL'}]},
  {'expected':'Diabète Type 1','age':16,'sexe':'F','sev':'SEVERE','duree':14,'vitaux':{'tension_systolique':108,'tension_diastolique':65,'frequence_cardiaque':105,'temperature':37.5,'frequence_respiratoire':22,'saturation_oxygene':98,'poids':42,'taille':162},'symptomes':['Soif excessive','Fréquence urinaire','Perte de poids','Fatigue','Nausées','Douleur abdominale'],'examens':[{'nom':'Glucose','valeur_numerique':320,'unite_mesure':'mg/dL'},{'nom':'HbA1c','valeur_numerique':11.5,'unite_mesure':'%'},{'nom':'Potassium','valeur_numerique':3.5,'unite_mesure':'mEq/L'},{'nom':'Sodium','valeur_numerique':130,'unite_mesure':'mEq/L'}]},
  {'expected':'Hypothyroïdie','age':44,'sexe':'F','sev':'MODERE','duree':90,'vitaux':{'tension_systolique':110,'tension_diastolique':70,'frequence_cardiaque':52,'temperature':36.0,'frequence_respiratoire':14,'saturation_oxygene':98,'poids':82,'taille':165},'symptomes':['Fatigue','Prise de poids','Froid excessif','Cheveux cassants','Peau sèche','Constipation','Dépression'],'examens':[{'nom':'Cholestérol total','valeur_numerique':265,'unite_mesure':'mg/dL'},{'nom':'Cholestérol LDL','valeur_numerique':180,'unite_mesure':'mg/dL'},{'nom':'Hémoglobine','valeur_numerique':10.5,'unite_mesure':'g/dL'}]},
  {'expected':'Hyperthyroïdie','age':32,'sexe':'F','sev':'MODERE','duree':30,'vitaux':{'tension_systolique':145,'tension_diastolique':70,'frequence_cardiaque':115,'temperature':37.8,'frequence_respiratoire':18,'saturation_oxygene':98,'poids':48,'taille':162},'symptomes':['Palpitations','Perte de poids','Intolérance à la chaleur','Tremblements','Nervosité','Yeux saillants'],'examens':[{'nom':'Glucose','valeur_numerique':115,'unite_mesure':'mg/dL'},{'nom':'Cholestérol total','valeur_numerique':140,'unite_mesure':'mg/dL'}]},
  {'expected':'Syndrome de Cushing','age':38,'sexe':'F','sev':'MODERE','duree':180,'vitaux':{'tension_systolique':155,'tension_diastolique':95,'frequence_cardiaque':88,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':97,'poids':90,'taille':162},'symptomes':['Prise de poids rapide','Grossissement du visage','Hypertension','Vergetures','Fatigue','Infections fréquentes'],'examens':[{'nom':'Glucose à jeun','valeur_numerique':145,'unite_mesure':'mg/dL'},{'nom':'Potassium','valeur_numerique':3.0,'unite_mesure':'mEq/L'},{'nom':'Sodium','valeur_numerique':148,'unite_mesure':'mEq/L'}]},
  {'expected':'Gastrite','age':34,'sexe':'M','sev':'LEGER','duree':10,'vitaux':{'tension_systolique':120,'tension_diastolique':75,'frequence_cardiaque':78,'temperature':37.1,'frequence_respiratoire':16,'saturation_oxygene':99,'poids':72,'taille':174},'symptomes':["Douleur épigastrique","Brûlures d'estomac",'Nausées','Ballonnements',"Perte d'appétit",'Rot'],'examens':[{'nom':'Hémoglobine','valeur_numerique':12.8,'unite_mesure':'g/dL'}]},
  {'expected':'RGO','age':42,'sexe':'F','sev':'LEGER','duree':30,'vitaux':{'tension_systolique':125,'tension_diastolique':78,'frequence_cardiaque':75,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':99,'poids':75,'taille':162},'symptomes':["Brûlures d'estomac",'Reflux gastro-esophagien','Régurgitation','Toux sèche','Difficulté à avaler'],'examens':[]},
  {'expected':'Ulcère gastro-duodénal','age':50,'sexe':'M','sev':'MODERE','duree':21,'vitaux':{'tension_systolique':118,'tension_diastolique':72,'frequence_cardiaque':88,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':98,'poids':70,'taille':170},'symptomes':['Douleur épigastrique','Douleur au repas','Nausées','Saignement digestif','Mélaena',"Perte d'appétit"],'examens':[{'nom':'Hémoglobine','valeur_numerique':9.5,'unite_mesure':'g/dL'},{'nom':'Hématocrite','valeur_numerique':28,'unite_mesure':'%'}]},
  {'expected':'Hépatite B','age':28,'sexe':'M','sev':'MODERE','duree':15,'vitaux':{'tension_systolique':112,'tension_diastolique':70,'frequence_cardiaque':82,'temperature':38.0,'frequence_respiratoire':17,'saturation_oxygene':98,'poids':70,'taille':172},'symptomes':['Ictère','Jaunisse','Fatigue','Douleur abdominale','Nausées','Selles pâles','Urine foncée'],'examens':[{'nom':'ALT/SGPT','valeur_numerique':680,'unite_mesure':'U/L'},{'nom':'AST/SGOT','valeur_numerique':540,'unite_mesure':'U/L'},{'nom':'Bilirubine totale','valeur_numerique':4.8,'unite_mesure':'mg/dL'},{'nom':'Albumine','valeur_numerique':3.0,'unite_mesure':'g/dL'}]},
  {'expected':'Cirrhose','age':58,'sexe':'M','sev':'SEVERE','duree':365,'vitaux':{'tension_systolique':108,'tension_diastolique':65,'frequence_cardiaque':95,'temperature':37.5,'frequence_respiratoire':18,'saturation_oxygene':95,'poids':80,'taille':170},'symptomes':['Ascite','Ictère','Hépatomégalie','Splenomégalie','Saignement digestif','Varices œsophagiennes','Confusion'],'examens':[{'nom':'Albumine','valeur_numerique':2.2,'unite_mesure':'g/dL'},{'nom':'PT/INR','valeur_numerique':2.1,'unite_mesure':''},{'nom':'Bilirubine totale','valeur_numerique':6.5,'unite_mesure':'mg/dL'},{'nom':'Plaquettes','valeur_numerique':85,'unite_mesure':'K/µL'}]},
  {'expected':'Insuffisance rénale chronique','age':65,'sexe':'M','sev':'SEVERE','duree':180,'vitaux':{'tension_systolique':158,'tension_diastolique':96,'frequence_cardiaque':80,'temperature':36.8,'frequence_respiratoire':18,'saturation_oxygene':96,'poids':80,'taille':170},'symptomes':['Fatigue','Nausées',"Perte d'appétit",'Gonflement des chevilles','Oligurie ou polyurie','Prurit'],'examens':[{'nom':'Créatinine','valeur_numerique':4.8,'unite_mesure':'mg/dL'},{'nom':'Urée','valeur_numerique':85,'unite_mesure':'mg/dL'},{'nom':'TFG','valeur_numerique':14,'unite_mesure':'mL/min/1.73m²'},{'nom':'Potassium','valeur_numerique':5.8,'unite_mesure':'mEq/L'}]},
  {'expected':'Lithiase rénale','age':38,'sexe':'M','sev':'SEVERE','duree':2,'vitaux':{'tension_systolique':130,'tension_diastolique':82,'frequence_cardiaque':108,'temperature':37.8,'frequence_respiratoire':20,'saturation_oxygene':98,'poids':80,'taille':175},'symptomes':['Douleur lombaire','Douleur colique intense','Hématurie','Nausées','Vomissements','Fréquence urinaire'],'examens':[{'nom':'Acide urique','valeur_numerique':9.2,'unite_mesure':'mg/dL'},{'nom':'Calcium','valeur_numerique':11.2,'unite_mesure':'mg/dL'},{'nom':'Créatinine','valeur_numerique':1.3,'unite_mesure':'mg/dL'}]},
  {'expected':'Cystite','age':26,'sexe':'F','sev':'LEGER','duree':3,'vitaux':{'tension_systolique':115,'tension_diastolique':70,'frequence_cardiaque':85,'temperature':37.9,'frequence_respiratoire':16,'saturation_oxygene':99,'poids':58,'taille':162},'symptomes':['Dysurie','Fréquence urinaire','Urgence urinaire','Douleur pelvienne','Urines foncées','Hématurie'],'examens':[]},
  {'expected':'Migraine','age':30,'sexe':'F','sev':'MODERE','duree':2,'vitaux':{'tension_systolique':118,'tension_diastolique':72,'frequence_cardiaque':75,'temperature':36.9,'frequence_respiratoire':15,'saturation_oxygene':99,'poids':60,'taille':165},'symptomes':['Maux de tête sévères','Nausées','Vomissements','Photophobie','Phonophobie','Aura','Vertiges'],'examens':[]},
  {'expected':'Épilepsie','age':20,'sexe':'M','sev':'SEVERE','duree':7,'vitaux':{'tension_systolique':122,'tension_diastolique':75,'frequence_cardiaque':88,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':97,'poids':68,'taille':172},'symptomes':['Convulsions','Perte de conscience','Fatigue post-critique','Confusion','Troubles cognitifs'],'examens':[{'nom':'Sodium','valeur_numerique':138,'unite_mesure':'mEq/L'}]},
  {'expected':'Accident vasculaire cérébral','age':68,'sexe':'M','sev':'CRITIQUE','duree':1,'vitaux':{'tension_systolique':180,'tension_diastolique':105,'frequence_cardiaque':88,'temperature':37.3,'frequence_respiratoire':20,'saturation_oxygene':94,'poids':82,'taille':172},'symptomes':['Faiblesse soudaine','Difficulté à parler','Paralysie','Troubles cognitifs','Perte de vision','Céphalées','Dysphagie'],'examens':[{'nom':'Glucose','valeur_numerique':155,'unite_mesure':'mg/dL'},{'nom':'Cholestérol total','valeur_numerique':248,'unite_mesure':'mg/dL'}]},
  {'expected':'Parkinson','age':72,'sexe':'M','sev':'MODERE','duree':365,'vitaux':{'tension_systolique':128,'tension_diastolique':78,'frequence_cardiaque':65,'temperature':36.8,'frequence_respiratoire':15,'saturation_oxygene':97,'poids':70,'taille':168},'symptomes':['Tremblements','Lenteur de mouvement','Rigidité',"Trouble de l'équilibre",'Difficulté à marcher','Constipation'],'examens':[]},
  {'expected':'Grippe','age':35,'sexe':'M','sev':'MODERE','duree':3,'vitaux':{'tension_systolique':118,'tension_diastolique':72,'frequence_cardiaque':98,'temperature':39.2,'frequence_respiratoire':19,'saturation_oxygene':97,'poids':75,'taille':175},'symptomes':['Fièvre élevée','Douleurs musculaires','Céphalées','Fatigue','Toux sèche','Congestion nasale','Frissons'],'examens':[{'nom':'Globules Blancs','valeur_numerique':4.2,'unite_mesure':'K/µL'}]},
  {'expected':'Typhoïde','age':18,'sexe':'M','sev':'SEVERE','duree':10,'vitaux':{'tension_systolique':105,'tension_diastolique':65,'frequence_cardiaque':75,'temperature':40.1,'frequence_respiratoire':18,'saturation_oxygene':97,'poids':60,'taille':168},'symptomes':['Fièvre élevée','Diarrhée','Douleur abdominale','Rash rose','Malaise général','Maux de tête',"Perte d'appétit"],'examens':[{'nom':'Globules Blancs','valeur_numerique':3.5,'unite_mesure':'K/µL'},{'nom':'Lymphocytes','valeur_numerique':40,'unite_mesure':'%'},{'nom':'Hémoglobine','valeur_numerique':11.0,'unite_mesure':'g/dL'}]},
  {'expected':'Paludisme','age':28,'sexe':'M','sev':'SEVERE','duree':5,'vitaux':{'tension_systolique':100,'tension_diastolique':62,'frequence_cardiaque':115,'temperature':40.5,'frequence_respiratoire':22,'saturation_oxygene':94,'poids':65,'taille':170},'symptomes':['Fièvre intermittente','Frissons','Sueurs','Maux de tête sévère','Douleurs musculaires','Nausées','Vomissements'],'examens':[{'nom':'Hémoglobine','valeur_numerique':7.8,'unite_mesure':'g/dL'},{'nom':'Plaquettes','valeur_numerique':65,'unite_mesure':'K/µL'}]},
  {'expected':'VIH/SIDA','age':32,'sexe':'M','sev':'SEVERE','duree':60,'vitaux':{'tension_systolique':108,'tension_diastolique':68,'frequence_cardiaque':92,'temperature':38.5,'frequence_respiratoire':20,'saturation_oxygene':93,'poids':55,'taille':172},'symptomes':['Perte de poids','Sueurs nocturnes','Lymphadénopathie','Infections fréquentes','Toux persistante','Fatigue','Diarrhée'],'examens':[{'nom':'Lymphocytes','valeur_numerique':8,'unite_mesure':'%'},{'nom':'Globules Blancs','valeur_numerique':3.2,'unite_mesure':'K/µL'},{'nom':'Hémoglobine','valeur_numerique':9.8,'unite_mesure':'g/dL'}]},
  {'expected':'Dengue','age':24,'sexe':'F','sev':'MODERE','duree':5,'vitaux':{'tension_systolique':102,'tension_diastolique':62,'frequence_cardiaque':68,'temperature':39.8,'frequence_respiratoire':18,'saturation_oxygene':97,'poids':55,'taille':160},'symptomes':['Fièvre élevée','Douleurs musculaires','Douleurs articulaires','Maux de tête sévère','Rash','Douleur oculaire','Fatigue'],'examens':[{'nom':'Plaquettes','valeur_numerique':48,'unite_mesure':'K/µL'},{'nom':'Hématocrite','valeur_numerique':48,'unite_mesure':'%'}]},
  {'expected':'Anémie ferriprive','age':28,'sexe':'F','sev':'MODERE','duree':30,'vitaux':{'tension_systolique':105,'tension_diastolique':65,'frequence_cardiaque':105,'temperature':36.8,'frequence_respiratoire':19,'saturation_oxygene':96,'poids':55,'taille':162},'symptomes':['Fatigue','Pâleur','Essoufflement','Vertiges','Palpitations','Cheveux cassants'],'examens':[{'nom':'Hémoglobine','valeur_numerique':7.2,'unite_mesure':'g/dL'},{'nom':'VGM','valeur_numerique':62,'unite_mesure':'fL'},{'nom':'CCMH','valeur_numerique':28,'unite_mesure':'g/dL'},{'nom':'Globules Rouges','valeur_numerique':3.2,'unite_mesure':'M/µL'}]},
  {'expected':'Leucémie','age':45,'sexe':'M','sev':'SEVERE','duree':30,'vitaux':{'tension_systolique':118,'tension_diastolique':72,'frequence_cardiaque':95,'temperature':38.2,'frequence_respiratoire':18,'saturation_oxygene':96,'poids':70,'taille':172},'symptomes':['Fatigue','Pâleur','Bleus faciles','Saignements','Infections fréquentes','Fièvre','Ganglions enflés','Douleurs osseuses'],'examens':[{'nom':'Globules Blancs','valeur_numerique':85,'unite_mesure':'K/µL'},{'nom':'Plaquettes','valeur_numerique':42,'unite_mesure':'K/µL'},{'nom':'Hémoglobine','valeur_numerique':7.5,'unite_mesure':'g/dL'}]},
  {'expected':'Thrombose veineuse','age':52,'sexe':'F','sev':'MODERE','duree':3,'vitaux':{'tension_systolique':132,'tension_diastolique':80,'frequence_cardiaque':90,'temperature':37.5,'frequence_respiratoire':18,'saturation_oxygene':96,'poids':80,'taille':165},'symptomes':["Gonflement d'un membre",'Douleur au bras','Chaleur','Rougeur cutanée','Claudication','Thrombose'],'examens':[{'nom':'PT/INR','valeur_numerique':1.0,'unite_mesure':''}]},
  {'expected':'Arthrite rhumatoïde','age':48,'sexe':'F','sev':'MODERE','duree':90,'vitaux':{'tension_systolique':122,'tension_diastolique':76,'frequence_cardiaque':80,'temperature':37.4,'frequence_respiratoire':16,'saturation_oxygene':98,'poids':68,'taille':162},'symptomes':['Douleurs articulaires','Raideur matinale','Gonflement','Fatigue','Douleurs musculaires','Restriction de mobilité'],'examens':[{'nom':'CRP','valeur_numerique':48,'unite_mesure':'mg/L'},{'nom':'ESR','valeur_numerique':65,'unite_mesure':'mm/h'},{'nom':'Hémoglobine','valeur_numerique':10.8,'unite_mesure':'g/dL'},{'nom':'Plaquettes','valeur_numerique':420,'unite_mesure':'K/µL'}]},
  {'expected':'Lupus érythémateux systémique','age':28,'sexe':'F','sev':'MODERE','duree':60,'vitaux':{'tension_systolique':138,'tension_diastolique':85,'frequence_cardiaque':92,'temperature':38.0,'frequence_respiratoire':17,'saturation_oxygene':97,'poids':58,'taille':160},'symptomes':['Éruption malaire','Photosensibilité','Douleurs articulaires','Fatigue','Fièvre','Rash photosensible','Ulcères buccaux'],'examens':[{'nom':'Globules Blancs','valeur_numerique':2.8,'unite_mesure':'K/µL'},{'nom':'Plaquettes','valeur_numerique':90,'unite_mesure':'K/µL'},{'nom':'Créatinine','valeur_numerique':1.5,'unite_mesure':'mg/dL'},{'nom':'Albumine','valeur_numerique':2.8,'unite_mesure':'g/dL'}]},
  {'expected':'Goutte','age':52,'sexe':'M','sev':'MODERE','duree':2,'vitaux':{'tension_systolique':148,'tension_diastolique':90,'frequence_cardiaque':85,'temperature':37.8,'frequence_respiratoire':16,'saturation_oxygene':98,'poids':95,'taille':174},'symptomes':['Douleur articulaire soudaine','Gonflement','Rougeur','Chaleur','Tophi','Douleurs articulaires'],'examens':[{'nom':'Acide urique','valeur_numerique':10.8,'unite_mesure':'mg/dL'},{'nom':'Créatinine','valeur_numerique':1.3,'unite_mesure':'mg/dL'},{'nom':'CRP','valeur_numerique':55,'unite_mesure':'mg/L'}]},
  {'expected':'Psoriasis','age':35,'sexe':'M','sev':'MODERE','duree':180,'vitaux':{'tension_systolique':125,'tension_diastolique':78,'frequence_cardiaque':76,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':99,'poids':80,'taille':175},'symptomes':['Plaques rouges squameuses','Prurit','Desquamation','Saignement des plaques','Douleurs articulaires','Raideur matinale'],'examens':[]},
  {'expected':'Eczéma','age':8,'sexe':'M','sev':'LEGER','duree':30,'vitaux':{'tension_systolique':98,'tension_diastolique':62,'frequence_cardiaque':90,'temperature':37.0,'frequence_respiratoire':18,'saturation_oxygene':99,'poids':25,'taille':128},'symptomes':['Démangeaisons','Éruption prurigineuse','Sécheresse cutanée','Rougeur cutanée','Vésicules','Crevasses'],'examens':[{'nom':'Eosinophiles','valeur_numerique':12,'unite_mesure':'%'},{'nom':'Globules Blancs','valeur_numerique':10.5,'unite_mesure':'K/µL'}]},
  {'expected':'Urticaire','age':24,'sexe':'F','sev':'MODERE','duree':1,'vitaux':{'tension_systolique':112,'tension_diastolique':70,'frequence_cardiaque':95,'temperature':37.2,'frequence_respiratoire':17,'saturation_oxygene':99,'poids':60,'taille':163},'symptomes':['Démangeaisons','Éruption cutanée','Angioedème','Gonflement des lèvres','Rougeur cutanée','Histaminémie'],'examens':[{'nom':'Eosinophiles','valeur_numerique':7,'unite_mesure':'%'}]},
  {'expected':'Conjonctivite','age':12,'sexe':'M','sev':'LEGER','duree':3,'vitaux':{'tension_systolique':100,'tension_diastolique':65,'frequence_cardiaque':85,'temperature':37.5,'frequence_respiratoire':17,'saturation_oxygene':99,'poids':38,'taille':148},'symptomes':['Yeux rouges','Rougeur oculaire','Larmoiement','Démangeaisons','Écoulement puriforme','Injection conjonctivale'],'examens':[]},
  {'expected':'Glaucome','age':65,'sexe':'F','sev':'MODERE','duree':180,'vitaux':{'tension_systolique':138,'tension_diastolique':85,'frequence_cardiaque':72,'temperature':36.8,'frequence_respiratoire':15,'saturation_oxygene':98,'poids':70,'taille':160},'symptomes':['Perte de vision progressive','Vision tunnel','Halos colorés','Douleur oculaire','Maux de tête'],'examens':[]},
  {'expected':'Rhinite allergique','age':22,'sexe':'M','sev':'LEGER','duree':14,'vitaux':{'tension_systolique':115,'tension_diastolique':70,'frequence_cardiaque':78,'temperature':36.9,'frequence_respiratoire':16,'saturation_oxygene':99,'poids':70,'taille':175},'symptomes':['Congestion nasale','Éternuements','Démangeaisons nasales','Écoulement nasal','Larmoiement','Fatigue oculaire'],'examens':[{'nom':'Eosinophiles','valeur_numerique':8,'unite_mesure':'%'}]},
  {'expected':'Pancréatite','age':42,'sexe':'M','sev':'SEVERE','duree':2,'vitaux':{'tension_systolique':100,'tension_diastolique':62,'frequence_cardiaque':115,'temperature':38.5,'frequence_respiratoire':24,'saturation_oxygene':94,'poids':85,'taille':175},'symptomes':['Douleur abdominale supérieure','Nausées','Vomissements','Fièvre','Douleur épigastrique','Malaise général'],'examens':[{'nom':'CRP','valeur_numerique':180,'unite_mesure':'mg/L'},{'nom':'Calcium','valeur_numerique':7.2,'unite_mesure':'mg/dL'}]},
  {'expected':'Syndrome du côlon irritable','age':32,'sexe':'F','sev':'MODERE','duree':180,'vitaux':{'tension_systolique':118,'tension_diastolique':72,'frequence_cardiaque':78,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':99,'poids':60,'taille':165},'symptomes':['Crampes abdominales','Ballonnements','Diarrhée','Constipation','Gaz','Besoin impérieux de déféquer','Anxiété'],'examens':[{'nom':'CRP','valeur_numerique':3,'unite_mesure':'mg/L'},{'nom':'Hémoglobine','valeur_numerique':12.5,'unite_mesure':'g/dL'}]},
  {'expected':'Embolie pulmonaire','age':55,'sexe':'F','sev':'CRITIQUE','duree':1,'vitaux':{'tension_systolique':95,'tension_diastolique':60,'frequence_cardiaque':125,'temperature':37.5,'frequence_respiratoire':30,'saturation_oxygene':85,'poids':72,'taille':162},'symptomes':['Essoufflement soudain','Douleur thoracique pleurétique','Palpitations','Syncope','Toux sèche','Hémoptysie'],'examens':[{'nom':'Troponine','valeur_numerique':0.8,'unite_mesure':'ng/mL'},{'nom':'BNP','valeur_numerique':620,'unite_mesure':'pg/mL'}]},
  {'expected':'Sclérose en plaques','age':28,'sexe':'F','sev':'MODERE','duree':14,'vitaux':{'tension_systolique':118,'tension_diastolique':72,'frequence_cardiaque':78,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':98,'poids':62,'taille':165},'symptomes':['Faiblesse','Engourdissement','Troubles cognitifs','Fatigue','Difficulté à marcher','Vision floue','Spasticité'],'examens':[]},
  {'expected':'Fibromyalgie','age':42,'sexe':'F','sev':'MODERE','duree':180,'vitaux':{'tension_systolique':120,'tension_diastolique':75,'frequence_cardiaque':80,'temperature':37.0,'frequence_respiratoire':16,'saturation_oxygene':99,'poids':70,'taille':163},'symptomes':['Douleurs musculaires diffuses','Fatigue','Troubles du sommeil','Maux de tête diffus','Anxiété','Dépression','Raideur matinale'],'examens':[{'nom':'CRP','valeur_numerique':2,'unite_mesure':'mg/L'},{'nom':'ESR','valeur_numerique':12,'unite_mesure':'mm/h'}]},
  {'expected':'Mononucléose','age':19,'sexe':'F','sev':'MODERE','duree':7,'vitaux':{'tension_systolique':110,'tension_diastolique':68,'frequence_cardiaque':98,'temperature':39.0,'frequence_respiratoire':18,'saturation_oxygene':97,'poids':55,'taille':162},'symptomes':['Mal de gorge','Ganglions enflés','Fatigue','Fièvre','Hépatomégalie','Splenomégalie','Rash rose'],'examens':[{'nom':'Lymphocytes','valeur_numerique':62,'unite_mesure':'%'},{'nom':'Globules Blancs','valeur_numerique':14.5,'unite_mesure':'K/µL'},{'nom':'ALT/SGPT','valeur_numerique':125,'unite_mesure':'U/L'}]},
]

correct = 0
top3_count = 0
results = []

for case in CASES:
    payload = {
        'age': case['age'], 'sexe': case['sexe'],
        'severite': case['sev'],
        'duree_symptomes_jours': case['duree'],
        'vitaux': case['vitaux'],
        'symptomes': case['symptomes'],
        'examens': case.get('examens', [])
    }
    r = requests.post('http://localhost:8000/api/ml/predict-direct', json=payload, headers=headers)
    d = r.json()
    predicted = d.get('diagnostic_propose','?')
    conf = d.get('confiance', 0)
    alts = [a['diagnostic'] for a in d.get('diagnostics_alternatifs',[])]
    all_top3 = [predicted] + alts

    ok = predicted == case['expected']
    ok3 = case['expected'] in all_top3
    if ok: correct += 1
    if ok3: top3_count += 1

    status = 'OK' if ok else ('TOP3' if ok3 else 'FAIL')
    results.append((status, case['expected'], predicted, conf))

print(f'=== RESULTATS BATCH 50 MALADIES ===')
print(f'Top-1 correct : {correct}/50  ({correct*2}%)')
print(f'Top-3 correct : {top3_count}/50  ({top3_count*2}%)')
print()
for i,(status,expected,predicted,conf) in enumerate(results, 1):
    icon = 'V' if status=='OK' else ('~' if status=='TOP3' else 'X')
    print(f'[{icon}] {i:2d}. Attendu: {expected:<38} | Predit: {predicted} ({conf*100:.0f}%)')
